# The `service` block is the name of the service
service: prograde-contact

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - ses:SendEmail
      Resource:
        - "arn:aws:ses:us-east-1:405906579827:identity/joey.gryder@gmail.com"
        - "arn:aws:ses:us-east-1:405906579827:identity/boxrrumble@gmail.com"

# The `functions` block defines what code to deploy
functions:
  submitContact:
    handler: handler.submitContact
    # The `events` block defines how to trigger the handler.submitContact code
    events:
      - http:
          path: contact
          method: post
          cors: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'api.joeygryder.com'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
